apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
data:
  krakend.json: |
    {
      "version": 3,
      "name": "KrakenD Gateway",
      "port": 8080,
      "cache_ttl": "3600s",
      "timeout": "3s",
      "endpoints": [
        {
          "endpoint": "/api/v1/users",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/api/v1/users",
              "host": ["http://user-service:8080"],
              "group": "users"
            }
          ]
        },
        {
          "endpoint": "/api/v1/products",
          "method": "GET",
          "backend": [
            {
              "url_pattern": "/api/v1/products",
              "host": ["http://product-service:8081"],
              "group": "products"
            }
          ]
        },
        {
          "endpoint": "/api/v1/login",
          "method": "POST",
          "backend": [
            {
              "url_pattern": "/api/v1/login",
              "host": ["http://user-service:8080"]
            }
          ]
        },
        {
          "endpoint": "/api/v1/register",
          "method": "POST",
          "backend": [
            {
              "url_pattern": "/api/v1/register",
              "host": ["http://user-service:8080"]
            }
          ]
        }
      ]
    } 