apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
data:
  config.yaml: |
    database:
      host: postgres
      port: 5432
      user: postgres
      password: postgres
      dbname: productgodb
      sslmode: disable
    server:
      port: 8081
      host: 0.0.0.0 