apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  config.yaml: |
    database:
      host: postgres
      port: 5432
      user: postgres
      password: postgres
      dbname: usergodb
      sslmode: disable
    server:
      port: 8080
      host: 0.0.0.0 