apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/namespaces/development-namespace.yaml

namespace: development

patches:
  - target:
      kind: Namespace
      name: development
    patch: |-
      - op: replace
        path: /metadata/labels/environment
        value: development 