apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/ingress/ingress.yaml

namespace: production

patches:
  - target:
      kind: Ingress
      name: app-ingress
    patch: |-
      - op: replace
        path: /metadata/annotations/nginx.ingress.kubernetes.io/ssl-redirect
        value: "true"
      - op: replace
        path: /spec/rules/0/host
        value: api.example.com
      - op: replace
        path: /spec/rules/1/host
        value: app.example.com
      - op: add
        path: /spec/tls
        value:
        - hosts:
          - api.example.com
          - app.example.com
          secretName: tls-secret 