apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/ingress/ingress.yaml

namespace: staging

patches:
  - target:
      kind: Ingress
      name: app-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.staging.local
      - op: replace
        path: /spec/rules/1/host
        value: app.staging.local 