apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/secrets/db-secret.yaml
  - ../../../base/secrets/tls-secret.yaml

namespace: production

# Production için farklı ve güvenli bir secret oluştur
secretGenerator:
  - name: db-secret
    type: Opaque
    literals:
      - username=postgres
      - password=prod_secure_password_123
  # TLS sertifikası için secret
  - name: tls-secret
    type: kubernetes.io/tls
    files:
      - tls.crt=./tls.crt
      - tls.key=./tls.key 