apiVersion: v1
kind: Service
metadata:
  name: krakend
  labels:
    app: krakend
spec:
  selector:
    app: krakend
  ports:
    - name: http
      port: 8082
      targetPort: http
  type: ClusterIP 