apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/namespaces/namespaces.yaml

namespace: production

patches:
  - target:
      kind: Namespace
      name: production
    patch: |-
      - op: replace
        path: /metadata/labels/environment
        value: production 