apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/services

namespace: development

patches:
  - target:
      kind: Service
      name: client
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
  - target:
      kind: Service
      name: krakend
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP 