apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/storage/postgres-pv.yaml
  - ../../../base/storage/postgres-pvc.yaml

namespace: production

patches:
  - target:
      kind: PersistentVolume
      name: postgres-pv
    patch: |-
      - op: replace
        path: /spec/capacity/storage
        value: 10Gi
  - target:
      kind: PersistentVolumeClaim
      name: postgres-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 10Gi 