apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/secrets

namespace: development

# Development için farklı bir secret oluştur
secretGenerator:
  - name: db-secret
    type: Opaque
    literals:
      - username=postgres
      - password=dev_password

patches:
  - target:
      kind: Secret
      name: db-secret
    patch: |-
      - op: replace
        path: /data/DB_PASSWORD
        value: ZGV2X3Bhc3N3b3Jk  # base64 encoded "dev_password" 