apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/namespaces
  - ../../base/deployments
  - ../../base/services
  - ../../base/ingress
  - ../../base/configmaps
  - ../../base/secrets

namespace: development

patches:
  - path: patches/client-deployment-patch.yaml
    target:
      kind: Deployment
      name: client
  - path: patches/krakend-deployment-patch.yaml
    target:
      kind: Deployment
      name: krakend
  - path: patches/product-deployment-patch.yaml
    target:
      kind: Deployment
      name: product
  - path: patches/user-deployment-patch.yaml
    target:
      kind: Deployment
      name: user
  - path: patches/client-service-patch.yaml
    target:
      kind: Service
      name: client
  - path: patches/krakend-service-patch.yaml
    target:
      kind: Service
      name: krakend
  - path: patches/ingress-patch.yaml
    target:
      kind: Ingress
      name: app-ingress
  - path: patches/client-config-patch.yaml
    target:
      kind: ConfigMap
      name: client-config
  - path: patches/krakend-config-patch.yaml
    target:
      kind: ConfigMap
      name: krakend-config
  - path: patches/db-secret-patch.yaml
    target:
      kind: Secret
      name: db-secret 