apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/configmaps

namespace: development

patches:
  - target:
      kind: ConfigMap
      name: client-config
    patch: |-
      - op: replace
        path: /data/API_URL
        value: http://krakend.development.svc.cluster.local
  - target:
      kind: ConfigMap
      name: krakend-config
    patch: |-
      - op: replace
        path: /data/endpoints.json
        value: |
          {
            "endpoints": [
              {
                "endpoint": "/api/v1/products",
                "backend": [
                  {
                    "url_pattern": "/products",
                    "host": ["http://product-service.development.svc.cluster.local:8080"]
                  }
                ]
              },
              {
                "endpoint": "/api/v1/users",
                "backend": [
                  {
                    "url_pattern": "/users",
                    "host": ["http://user-service.development.svc.cluster.local:8080"]
                  }
                ]
              }
            ]
          } 