apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/secrets/db-secret.yaml

namespace: staging

# Staging için farklı bir secret oluştur
secretGenerator:
  - name: db-secret
    type: Opaque
    literals:
      - username=postgres
      - password=staging_password 