apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/namespaces/namespaces.yaml

namespace: staging

patches:
  - target:
      kind: Namespace
      name: staging
    patch: |-
      - op: replace
        path: /metadata/labels/environment
        value: staging 