apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # Bu değerler base64 encoded olmalı
  # echo -n "postgres" | base64
  username: cG9zdGdyZXM=
  # echo -n "postgres" | base64
  password: cG9zdGdyZXM= 