apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: kubernetes.io/tls
data:
  # Bu değerler production'da gerçek sertifika ile değiştirilecek
  tls.crt: base64_encoded_certificate
  tls.key: base64_encoded_private_key 