apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/namespaces
  - ../../base/deployments
  - ../../base/services
  - ../../base/ingress
  - ../../base/configmaps
  - ../../base/secrets
  - ./namespaces
  - ./deployments
  - ./services
  - ./ingress
  - ./configmaps
  - ./secrets
  - ./storage

namespace: staging 